### ISSUE TITLE
Suggestion Widget Box Unable to View hints, black on black

### ISSUE THREAD

**Issue by w-keys** [hayzey/vscode-themes#2]
![image](https://user-images.githubusercontent.com/89110154/179801046-41f7036d-af89-462c-b0be-0fdc010588ea.png)
Unable to view hints on right side of widget unless hovering over each individual one because of "black on black" like colour config. Any idea what to change in the .json

![image](https://user-images.githubusercontent.com/89110154/179801909-5b5e4d1b-e0ed-46f5-b45d-35cddadb7a7c.png)

**Comment by Bambinoclos** [comment]
Hope this helps. I changed the dark text color to a shade of white in my text editor by adding this in the VSCode json settings:

"workbench.colorCustomizations": {
        "editorSuggestWidget.foreground": "#F5F6FA"
}

**Comment by Bambinoclos** [comment]
> ![image](https://user-images.githubusercontent.com/89110154/179801046-41f7036d-af89-462c-b0be-0fdc010588ea.png) Unable to view hints on right side of widget unless hovering over each individual one because of "black on black" like colour config. Any idea what to change in the .json
> 
> ![image](https://user-images.githubusercontent.com/89110154/179801909-5b5e4d1b-e0ed-46f5-b45d-35cddadb7a7c.png)

Hope this helps. I changed the dark text color to a shade of white in my text editor by adding this in the VSCode json settings:

"workbench.colorCustomizations": {
        "editorSuggestWidget.foreground": "#F5F6FA"
}

**Comment by Bambinoclos** [comment]
I had that same problem. Hope this helps. I changed the dark text color to a shade of white in my text editor by adding this in the VSCode json settings:

"workbench.colorCustomizations": {
        "editorSuggestWidget.foreground": "#F5F6FA"
}

**Comment by THeK3nger** [comment]
@Bambinoclos Good job, Lieutenant. I will propose you for a commendation to Starfleet.

![godjob](https://user-images.githubusercontent.com/133159/216098908-bf254e18-4fdb-4631-af3e-fe77972cd67d.gif)

**Comment by spacesuitguy** [comment]
Bug still exists.

**Comment by hayzey** [comment]
Hi peeps! Sorry it's taken me so long to get to this, must've gotten lost in my notifications. I actually implemented this exact fix myself a long time ago in my local `settings.json` but just forgot to ever update the theme itself 😅

I'll go review that linked PR now - https://github.com/hayzey/vscode-themes/pull/3

**Comment by hayzey** [comment]
I've just merged that PR and published a new version, which should show up on the VS Code Marketplace soon.
